# Generated by Django 5.2.7 on 2025-10-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transactions",
            fields=[
                (
                    "transaction_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("correlation_id", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("sender_account", models.CharField(max_length=255)),
                ("receiver_account", models.CharField(max_length=255)),
                ("amount", models.IntegerField()),
                ("transaction_type", models.CharField(max_length=30)),
                ("merchant_category", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionsTypes",
            fields=[
                (
                    "transaction_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("transaction_type", models.CharField(max_length=30)),
            ],
        ),
    ]
