# Generated by Django 5.2.7 on 2025-10-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='correlation_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionstypes',
            name='transaction_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
