# Generated by Django 5.2.7 on 2025-10-22 13:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_transactions_correlation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correlation_id', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('component', models.CharField(choices=[('ingest', 'Ingest'), ('queue', 'Queue'), ('rules', 'Rules Engine'), ('notify', 'Notification')], max_length=20)),
                ('message', models.TextField()),
                ('structured_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='posts.transactions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
