# Generated by Django 5.2.7 on 2025-10-22 20:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=64, unique=True)),
                ('correlation_id', models.CharField(max_length=64)),
                ('data', models.JSONField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionQueueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('component', models.CharField(default='queue', max_length=50)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='posts.transactionqueue')),
            ],
        ),
    ]
