# Generated by Django 5.2.7 on 2025-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_transactions_options_transactions_api_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='device_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='fraud_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='geo_anomaly_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='spending_deviation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='time_since_last_transaction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='velocity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='correlation_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='merchant_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
