# Generated by Django 5.2.7 on 2025-10-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_transactions_device_hash_transactions_fraud_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrules',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalrules',
            name='rule_type',
            field=models.CharField(choices=[('threshold', 'Threshold'), ('pattern', 'Pattern'), ('composite', 'Composite')], default='threshold', max_length=20),
        ),
        migrations.AddField(
            model_name='rules',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='rules',
            name='rule_type',
            field=models.CharField(choices=[('threshold', 'Threshold'), ('pattern', 'Pattern'), ('composite', 'Composite')], default='threshold', max_length=20),
        ),
    ]
