# Generated by Django 5.2.7 on 2025-10-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_historicalrules_config_historicalrules_rule_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrules',
            name='config',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='config',
        ),
        migrations.AddField(
            model_name='historicalrules',
            name='composite_conditions',
            field=models.JSONField(blank=True, help_text='Список условий для composite', null=True),
        ),
        migrations.AddField(
            model_name='historicalrules',
            name='pattern_max_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrules',
            name='pattern_max_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrules',
            name='pattern_window_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalrules',
            name='threshold_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='composite_conditions',
            field=models.JSONField(blank=True, help_text='Список условий для composite', null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='pattern_max_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='pattern_max_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='pattern_window_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='threshold_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalrules',
            name='rule_type',
            field=models.CharField(choices=[('threshold', 'Threshold'), ('pattern', 'Pattern'), ('composite', 'Composite')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rules',
            name='rule_type',
            field=models.CharField(choices=[('threshold', 'Threshold'), ('pattern', 'Pattern'), ('composite', 'Composite')], max_length=20),
        ),
    ]
