# Generated by Django 5.2.7 on 2025-10-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_historicalrules_config_remove_rules_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrules',
            name='operator',
            field=models.CharField(blank=True, choices=[('>', 'Greater than (>)'), ('<', 'Less than (<)'), ('>=', 'Greater or equal (>=)'), ('<=', 'Less or equal (<=)'), ('==', 'Equal (==)')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='operator',
            field=models.CharField(blank=True, choices=[('>', 'Greater than (>)'), ('<', 'Less than (<)'), ('>=', 'Greater or equal (>=)'), ('<=', 'Less or equal (<=)'), ('==', 'Equal (==)')], max_length=2, null=True),
        ),
    ]
