# Generated by Django 5.2.7 on 2025-10-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_historicalrules_operator_rules_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='correlation_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID корреляции для трассировки между системами', max_length=50, null=True),
        ),
    ]
