# Generated by Django 5.2.7 on 2025-10-23 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_historicalrules_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.transactions'),
        ),
    ]
